import { router } from 'expo-router';
import { ChevronLeft, FileText, ShieldCheck } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { AppButton } from '@/shared/components/app-button';
import { Screen } from '@/shared/components/screen';
import { paymentService, type PaymentProvider } from '@/features/payments/services/payment-service';
const options: { id: PaymentProvider; label: string }[] = [{ id: 'paychangu', label: 'PayChangu' }, { id: 'airtel_money', label: 'Airtel Money' }, { id: 'tnm_mpamba', label: 'TNM Mpamba' }, { id: 'bank_transfer', label: 'Bank transfer' }];
export default function Payments() { const [provider, setProvider] = useState<PaymentProvider>('paychangu'); const [loading, setLoading] = useState(false); const pay = async () => { setLoading(true); try { const result = await paymentService.createPayment({ bookingId: 'demo-booking', amountMwk: 50000, provider, customerEmail: 'member@builderlink.mw' }); Alert.alert('Payment initiated', `Reference: ${result.reference}\nYou will be redirected to complete payment securely.`); } catch { Alert.alert('Payment failed', 'We couldn’t start your payment. Please check your connection and try again.'); } finally { setLoading(false); } }; return <Screen><Pressable onPress={() => router.back()} className="h-11 w-11 items-center justify-center rounded-2xl bg-white"><ChevronLeft color="#1E293B" /></Pressable><Text className="mt-6 text-3xl font-extrabold text-ink">Pay deposit</Text><Text className="mt-2 text-slate-500">Booking with Thoko Mbewe</Text><View className="mt-7 rounded-3xl bg-white p-5"><Text className="text-sm text-slate-500">Deposit due</Text><Text className="mt-1 text-3xl font-extrabold text-ink">MWK 50,000</Text><Text className="mt-2 text-sm text-slate-500">Your payment is held against this booking.</Text></View><Text className="mt-8 text-lg font-bold text-ink">Choose payment method</Text><View className="mt-3 gap-3">{options.map((option) => <Pressable key={option.id} onPress={() => setProvider(option.id)} className={`rounded-2xl border p-4 ${provider === option.id ? 'border-brand bg-orange-50' : 'border-slate-200 bg-white'}`}><Text className="font-bold text-ink">{option.label}</Text></Pressable>)}</View><View className="mt-6 flex-row gap-3 rounded-2xl bg-green-50 p-4"><ShieldCheck color="#16A34A" size={22} /><Text className="flex-1 leading-5 text-green-800">Payments are processed securely. Builder payouts are released after job completion.</Text></View><View className="mt-7 gap-3"><AppButton label="Continue to secure payment" loading={loading} onPress={pay} /><Pressable onPress={() => Alert.alert('Receipt preview', 'A detailed receipt will be available after payment is confirmed.')} className="flex-row items-center justify-center gap-2 py-2"><FileText size={18} color="#F97316" /><Text className="font-semibold text-brand">View receipt details</Text></Pressable></View></Screen>; }
