
-- BuilderLink Malawi core schema. Firebase Auth UID is stored as text because
-- Firebase UIDs are not guaranteed to be UUIDs.
create type public.user_role as enum ('customer', 'builder', 'administrator');
create type public.verification_status as enum ('pending', 'verified', 'rejected');
create type public.booking_status as enum ('pending', 'accepted', 'rejected', 'in_progress', 'completed', 'cancelled');
create type public.payment_status as enum ('pending', 'paid', 'failed', 'refunded');
create type public.document_type as enum ('national_id', 'certificate', 'license');

create table public.profiles (
  id text primary key, role public.user_role not null default 'customer', full_name text not null check (char_length(full_name) between 2 and 120), phone text, email text, avatar_path text, district text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, icon text, created_at timestamptz not null default now());
create table public.skills (id uuid primary key default gen_random_uuid(), category_id uuid references public.categories(id) on delete set null, name text not null unique);
create table public.builders (
  profile_id text primary key references public.profiles(id) on delete cascade, business_name text, bio text check (char_length(bio) <= 2000), years_experience smallint not null default 0 check (years_experience between 0 and 80), verification_status public.verification_status not null default 'pending', average_rating numeric(3,2) not null default 0 check (average_rating between 0 and 5), completed_jobs integer not null default 0 check (completed_jobs >= 0), response_time_minutes integer check (response_time_minutes >= 0), latitude numeric(9,6), longitude numeric(9,6), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.builder_skills (builder_id text references public.builders(profile_id) on delete cascade, skill_id uuid references public.skills(id) on delete cascade, primary key (builder_id, skill_id));
create table public.availability (id uuid primary key default gen_random_uuid(), builder_id text not null references public.builders(profile_id) on delete cascade, available_on date not null, is_available boolean not null default true, unique(builder_id, available_on));
create table public.portfolio_items (id uuid primary key default gen_random_uuid(), builder_id text not null references public.builders(profile_id) on delete cascade, storage_path text not null unique, caption text check (char_length(caption) <= 500), created_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), builder_id text not null references public.builders(profile_id) on delete cascade, type public.document_type not null, storage_path text not null unique, review_status public.verification_status not null default 'pending', created_at timestamptz not null default now());
create table public.bookings (id uuid primary key default gen_random_uuid(), customer_id text not null references public.profiles(id), builder_id text not null references public.builders(profile_id), category_id uuid references public.categories(id), status public.booking_status not null default 'pending', scheduled_for timestamptz, location_text text not null, description text not null check (char_length(description) <= 3000), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.booking_images (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id) on delete cascade, storage_path text not null unique, created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id), customer_id text not null references public.profiles(id), amount_mwk numeric(14,2) not null check (amount_mwk > 0), provider text not null, status public.payment_status not null default 'pending', provider_reference text unique, created_at timestamptz not null default now());
create table public.reviews (id uuid primary key default gen_random_uuid(), booking_id uuid not null unique references public.bookings(id), customer_id text not null references public.profiles(id), builder_id text not null references public.builders(profile_id), overall_rating smallint not null check (overall_rating between 1 and 5), comment text check (char_length(comment) <= 2000), created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id) on delete cascade, sender_id text not null references public.profiles(id), body text check (char_length(body) <= 4000), attachment_path text, read_at timestamptz, created_at timestamptz not null default now(), check (body is not null or attachment_path is not null));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id text not null references public.profiles(id) on delete cascade, title text not null, body text not null, data jsonb not null default '{}'::jsonb, read_at timestamptz, created_at timestamptz not null default now());
create table public.favorites (customer_id text references public.profiles(id) on delete cascade, builder_id text references public.builders(profile_id) on delete cascade, created_at timestamptz not null default now(), primary key(customer_id,builder_id));
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id text not null references public.profiles(id), reported_builder_id text references public.builders(profile_id), reason text not null check (char_length(reason) <= 2000), created_at timestamptz not null default now());
create table public.admin_logs (id uuid primary key default gen_random_uuid(), admin_id text not null references public.profiles(id), action text not null, target_type text not null, target_id text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index bookings_customer_idx on public.bookings(customer_id, created_at desc); create index bookings_builder_idx on public.bookings(builder_id, created_at desc); create index messages_booking_idx on public.messages(booking_id, created_at); create index notifications_user_idx on public.notifications(user_id, created_at desc); create index portfolio_builder_idx on public.portfolio_items(builder_id); create index documents_builder_idx on public.documents(builder_id);

alter table public.profiles enable row level security; alter table public.builders enable row level security; alter table public.categories enable row level security; alter table public.skills enable row level security; alter table public.builder_skills enable row level security; alter table public.availability enable row level security; alter table public.portfolio_items enable row level security; alter table public.documents enable row level security; alter table public.bookings enable row level security; alter table public.booking_images enable row level security; alter table public.payments enable row level security; alter table public.reviews enable row level security; alter table public.messages enable row level security; alter table public.notifications enable row level security; alter table public.favorites enable row level security; alter table public.reports enable row level security; alter table public.admin_logs enable row level security;

-- Firebase Auth's subject is read directly from its verified JWT.
create policy "read own profile" on public.profiles for select to authenticated using (id = (select auth.jwt() ->> 'sub'));
create policy "create own customer profile" on public.profiles for insert to authenticated with check (id = (select auth.jwt() ->> 'sub') and role = 'customer');
create policy "update own profile without role changes" on public.profiles for update to authenticated using (id = (select auth.jwt() ->> 'sub')) with check (id = (select auth.jwt() ->> 'sub') and role = (select p.role from public.profiles p where p.id = (select auth.jwt() ->> 'sub')));
create policy "read verified builders" on public.builders for select to authenticated using (verification_status = 'verified' or profile_id = (select auth.jwt() ->> 'sub'));
create policy "manage own builder" on public.builders for all to authenticated using (profile_id = (select auth.jwt() ->> 'sub')) with check (profile_id = (select auth.jwt() ->> 'sub'));
create policy "read catalogue" on public.categories for select to authenticated using (true); create policy "read skills" on public.skills for select to authenticated using (true);
create policy "own builder skills" on public.builder_skills for all to authenticated using (builder_id = (select auth.jwt() ->> 'sub')) with check (builder_id = (select auth.jwt() ->> 'sub'));
create policy "own availability" on public.availability for all to authenticated using (builder_id = (select auth.jwt() ->> 'sub')) with check (builder_id = (select auth.jwt() ->> 'sub'));
create policy "own portfolio" on public.portfolio_items for all to authenticated using (builder_id = (select auth.jwt() ->> 'sub')) with check (builder_id = (select auth.jwt() ->> 'sub'));
create policy "own documents" on public.documents for all to authenticated using (builder_id = (select auth.jwt() ->> 'sub')) with check (builder_id = (select auth.jwt() ->> 'sub'));
create policy "booking participants" on public.bookings for select to authenticated using (customer_id = (select auth.jwt() ->> 'sub') or builder_id = (select auth.jwt() ->> 'sub'));
create policy "customer creates booking" on public.bookings for insert to authenticated with check (customer_id = (select auth.jwt() ->> 'sub'));
create policy "booking participants read messages" on public.messages for select to authenticated using (exists (select 1 from public.bookings b where b.id = booking_id and (b.customer_id = (select auth.jwt() ->> 'sub') or b.builder_id = (select auth.jwt() ->> 'sub'))));
create policy "booking participants send messages" on public.messages for insert to authenticated with check (sender_id = (select auth.jwt() ->> 'sub') and exists (select 1 from public.bookings b where b.id = booking_id and (b.customer_id = (select auth.jwt() ->> 'sub') or b.builder_id = (select auth.jwt() ->> 'sub'))));
create policy "own notifications" on public.notifications for select to authenticated using (user_id = (select auth.jwt() ->> 'sub')); create policy "own favorites" on public.favorites for all to authenticated using (customer_id = (select auth.jwt() ->> 'sub')) with check (customer_id = (select auth.jwt() ->> 'sub')); create policy "create report" on public.reports for insert to authenticated with check (reporter_id = (select auth.jwt() ->> 'sub'));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('avatars','avatars',false,5242880,array['image/jpeg','image/png','image/webp']),('portfolio','portfolio',false,10485760,array['image/jpeg','image/png','image/webp']),('documents','documents',false,10485760,array['image/jpeg','image/png','application/pdf']),('booking-images','booking-images',false,10485760,array['image/jpeg','image/png','image/webp']) on conflict (id) do nothing;
create policy "users manage own storage" on storage.objects for all to authenticated using ((storage.foldername(name))[1] = (select auth.jwt() ->> 'sub')) with check ((storage.foldername(name))[1] = (select auth.jwt() ->> 'sub'));
